- name: play level
  hosts: local
  connection: local
  vars:
    course: "ansible"
    duaration: "140hrs"
    trainer: "chai"
  tasks:
    name: print the varaibles
    ansible.builtin.debug:
    msg: "couse is {{ course }}, Trainer is {{ trainer }}"